#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#
# Ruby
# 
if which rbenv > /dev/null; then
    eval "$(rbenv init -)"
fi

alias gst='git status'
alias ga='git add'
alias gap='git add --patch'
alias be='bundle exec'
alias stmux="if tmux has-session -t $USER; then tmux attach -t $USER; else tmux new -s $USER; fi"
